### ISSUE TITLE
Update Readme.md to have project setup 

### ISSUE THREAD

**Issue by Pradhvan** [nightwarrior-xxx/social#2]
This is the bare necessary step of project setup, you can add few more details in the readme for other devs or end-users to set up the project in their system.

#### 1. Create & activate the virtual environment 

```Bash
python3 -m venv test
source test/bin/activate 
```
#### 2. Install the dependencies 

```BASH
pip install -r requirements.txt
```

#### 3. Create a super user & Run server: 

```BASH
python manage.py createsuperuser 
python manange.py runserver 
```

**Comment by nightwarrior-xxx** [comment]
@Pradhvan Thanks for reminding . Will surely add it.

**Comment by Pradhvan** [comment]
@nightwarrior-xxx you only close an issue when it's done :smile:

**Comment by nightwarrior-xxx** [comment]
@Pradhvan Done

**Comment by Pradhvan** [comment]
@nightwarrior-xxx  Mention the PR that you did and close the issue.
